# Generated by Django 4.1.1 on 2023-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('date_of_creation', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=3000)),
                ('manager_id', models.IntegerField()),
                ('leader_id', models.IntegerField()),
                ('date_of_creation', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_start', models.DateTimeField()),
                ('date_of_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=3000)),
                ('project_id', models.IntegerField()),
                ('executor_id', models.IntegerField()),
                ('lead_id', models.IntegerField()),
                ('reviewer_id', models.IntegerField()),
                ('date_of_creation', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('date_of_start', models.DateTimeField()),
                ('story_point', models.IntegerField()),
                ('date_of_completion', models.DateTimeField()),
                ('sprint_id', models.IntegerField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('role', models.IntegerField(default=3)),
                ('project_id', models.IntegerField(default=0)),
                ('icon', models.ImageField(default='default-user.png', upload_to='')),
            ],
        ),
    ]
