# Generated by Django 4.1.1 on 2023-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=3000)),
                ('manager_id', models.IntegerField()),
                ('leader_id', models.IntegerField()),
                ('date_of_creation', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=3000)),
                ('project_id', models.IntegerField()),
                ('executor_id', models.IntegerField()),
                ('lead_id', models.IntegerField()),
                ('reviewer_id', models.IntegerField()),
                ('date_of_creation', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('story_point', models.IntegerField()),
                ('date_of_completion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('role', models.IntegerField()),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
