# Generated by Django 4.1.1 on 2023-04-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('date_of_creation', models.DateTimeField()),
            ],
        ),
    ]
