# Generated by Django 4.1.1 on 2023-05-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
