# Generated by Django 4.1.1 on 2023-05-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_remove_task_end_date_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_of_completion',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_of_start',
        ),
    ]
