# Generated by Django 4.1.1 on 2023-04-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('date_of_start', models.DateTimeField()),
                ('date_of_end', models.DateTimeField()),
            ],
        ),
    ]
