# Generated by Django 4.1.1 on 2023-04-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sprint_id',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
