# Generated by Django 4.1.1 on 2023-04-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_task_sprint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='task_id',
        ),
    ]
